services:
  # Frontend - React App
  - type: web
    name: peerpulse-frontend
    env: static
    buildCommand: cd production_app/frontend && npm ci && npm run build
    staticPublishPath: ./production_app/frontend/build
    headers:
      - path: /*
        name: X-Frame-Options
        value: DENY
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

  # Backend - FastAPI
  - type: web
    name: peerpulse-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python v3_demo_server.py
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: PORT
        value: 8000
    healthCheckPath: /